pipeline:
  name: p1
  identifier: p1
  projectIdentifier: old_git_proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: Users
      type: Number
      default: 1
      description: ""
      value: <+input>.allowedValues(1,2,3,4,7)
