pipeline:
  name: chetan_demo
  identifier: chetan_demo
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: s1_temp
          versionLabel: v1
