pipeline:
  name: error_t1
  identifier: error_t1
  projectIdentifier: vivek_qa_test
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: a1
                  identifier: a1
                  template:
                    templateRef: t1
                    versionLabel: v1
                    templateInputs:
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
        tags: {}
