pipeline:
  name: p1
  identifier: p1
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: d1
            identifier: d1
            description: ""
            type: Deployment
            spec:
              serviceConfig:
                serviceRef: srv1
                serviceDefinition:
                  spec:
                    variables: []
                  type: Kubernetes
              infrastructure:
                environmentRef: env1
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: cn1
                    namespace: n1
                    releaseName: release-<+INFRA_KEY>
                allowSimultaneousDeployments: true
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: sh1
                      identifier: sh1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Hello"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                rollbackSteps: []
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: d2
            identifier: d2
            description: ""
            type: Deployment
            spec:
              serviceConfig:
                useFromStage:
                  stage: d1
                stageOverrides:
                  artifacts:
                    sidecars: []
                  manifests: []
                  variables: []
              infrastructure:
                environmentRef: env1
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: cn1
                    namespace: n2
                    releaseName: release-<+INFRA_KEY>
                allowSimultaneousDeployments: true
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: SH
                      identifier: SH
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Hello"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                rollbackSteps: []
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: d3
            identifier: d3
            description: ""
            type: Deployment
            spec:
              serviceConfig:
                useFromStage:
                  stage: d1
              infrastructure:
                environmentRef: env1
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: cn1
                    namespace: n1
                    releaseName: release-<+INFRA_KEY>
                allowSimultaneousDeployments: false
              execution:
                steps:
                  - step:
                      type: ShellScript
                      name: sh1
                      identifier: sh1
                      spec:
                        shell: Bash
                        onDelegate: true
                        source:
                          type: Inline
                          spec:
                            script: echo "Hello"
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                rollbackSteps: []
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: s2
        identifier: s2
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs:
                      - name: aefwe
                        defaultValue: sdfseg
                      - name: feewg
                        defaultValue: fsdefg
                      - name: adfdsf
                        defaultValue: fdsedf
                      - name: asfsfs
                        defaultValue: asfsdf
                      - name: asfsef
                        defaultValue: asfdsdfgrw
                      - name: asfsdf
                        defaultValue: afsf
                      - name: adfsefse
                        defaultValue: fdsefwe
        tags: {}
