pipeline:
  name: git_pp_with_metadata
  identifier: git_pp_with_metadata
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: Please review the following information
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    approverInputs: []
        tags: {}
