pipeline:
  name: git_pp3
  identifier: git_pp3
  projectIdentifier: vivek_proj_stree
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ap1
        identifier: ap1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Another_Stage"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: ap2
        identifier: ap2
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: step2
                  identifier: step2
                  template:
                    templateRef: step_tmplt
                    versionLabel: Version1
        tags: {}
