pipeline:
  name: p1
  identifier: p1
  projectIdentifier: proj1_newgitx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  template:
                    templateRef: stept1
                    versionLabel: v1
                    templateInputs:
                      type: HarnessApproval
                      spec:
                        approvers:
                          minimumCount: <+input>
                          userGroups: <+input>
        tags: {}
