pipeline:
  name: remote_vivek
  identifier: remote_vivek
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh2
                  identifier: sh2
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>.executionInput()
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  failureStrategies: []
        tags: {}
    - stage:
        name: s2
        identifier: s3
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
                  failureStrategies: []
        tags: {}
        variables:
          - name: var1
            type: String
            default: ""
            description: ""
            value: <+input>.executionInput()
          - name: var2
            type: Number
            default: 4
            description: ""
            value: <+input>.executionInput().default(4)
