pipeline:
  name: test2
  identifier: test2
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        template:
          templateRef: t1
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: ap1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
