pipeline:
  name: test
  identifier: test
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ap1
        identifier: ap1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  template:
                    templateRef: app_t
                    versionLabel: v1
                    templateInputs:
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
        tags: {}
