pipeline:
  name: vivek_pp
  identifier: vivek_pp
  projectIdentifier: vivek
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: bug_app1
        identifier: bug_app1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: app2
                  identifier: app2
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
