pipeline:
  name: "vivek_pipeline_3"
  identifier: "vivek_pipeline_3"
  projectIdentifier: "Ramyasimplegit"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "approval 1"
      identifier: "approval_1"
      description: "This is to imported from Git"
      type: "Approval"
      spec:
        execution:
          steps:
          - step:
              name: "approval 1"
              identifier: "approval_1"
              type: "HarnessApproval"
              timeout: "1d"
              spec:
                approvalMessage: "Please review the following information\nand approve\
                  \ the pipeline progression"
                includePipelineExecutionHistory: true
                approvers:
                  minimumCount: 1
                  disallowPipelineExecutor: false
                  userGroups: "<+input>"
                approverInputs: []
      tags: {}
  description: ""
