pipeline:
  name: p1_Remote
  identifier: p1_Remote
  projectIdentifier: proj1_PR_ENV
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: srv1
            serviceDefinition:
              spec:
                variables: []
              type: Kubernetes
          infrastructure:
            environmentRef: env1
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: k8s_con
                namespace: n1
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
