pipeline:
  name: old_git_pp
  identifier: old_git_pp
  projectIdentifier: proj1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: srv1
            serviceDefinition:
              spec:
                variables: []
              type: Kubernetes
          infrastructure:
            environmentRef: env1
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: k8s_con_tisuccess
                namespace: n1
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: sh1
                  identifier: sh1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "Hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: ap1
        identifier: ap1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: ap1
                  identifier: ap1
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: <+input>
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
